# Lv.3 대여 횟수가 많은 자동차들의 월별 대여 횟수 구하기
SELECT
    DATE_FORMAT(START_DATE, '%m') AS MONTH,
    CAR_ID,
    COUNT(*) AS RECORDS
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE # CAR_ID를 기준으로 묶었을 때 그 합이 5 이상인 CAR_ID 중에서 + 날짜 조건 포함 
    CAR_ID IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
        GROUP BY CAR_ID
        HAVING COUNT(*) >= 5
    ) AND START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY
    MONTH,
    CAR_ID
ORDER BY
    MONTH,
    CAR_ID DESC;