# Lv 2. 자동차 평균 대여 기간 구하기
SELECT CAR_ID, ROUND(AVG(duration)+1,1) as AVERAGE_DURATION FROM (SELECT CAR_ID, DATEDIFF(END_DATE, START_DATE) as duration FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) as c1
GROUP BY CAR_ID
# DATEDIFF를 하면 일수가 하나 줄어드니까 +1 해줘야한다. 
HAVING AVERAGE_DURATION>=7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC;
