# Lv4. 저자 별 카테고리 별 매출액 집계하기
SELECT a1.AUTHOR_ID, a1.AUTHOR_NAME, b2.CATEGORY, SUM(b1.SALES*b2.PRICE) as TOTAL_SALES FROM (SELECT * FROM BOOK_SALES WHERE SALES_DATE LIKE '2022-01%') as b1 
LEFT JOIN BOOK b2
ON b1.BOOK_ID=b2.BOOK_ID
LEFT JOIN AUTHOR a1
ON b2.AUTHOR_ID = a1.AUTHOR_ID
GROUP BY a1.AUTHOR_ID, b2.CATEGORY
ORDER BY a1.AUTHOR_ID ASC, b2.CATEGORY DESC;