# Lv4. 취소되지 않은 진료 예약 조회하기
SELECT a.APNT_NO, p.PT_NAME, p.PT_NO, d.MCDP_CD, d.DR_NAME, a.APNT_YMD FROM APPOINTMENT a
LEFT JOIN DOCTOR d
ON a.MDDR_ID=d.DR_ID
LEFT JOIN PATIENT p
ON a.PT_NO=p.PT_NO
WHERE d.MCDP_CD ='CS'AND
a.APNT_YMD LIKE '2022-04-13%' AND
a.APNT_CNCL_YN ='N'
ORDER BY a.APNT_YMD ASC;
