# Lv.4 서울에 위치한 식당 목록 출력하기
# GROUP BY 때문에 조건 헷갈리기 싫으니까 서브쿼리로 묶기
SELECT r1.REST_ID, r1.REST_NAME, r1.FOOD_TYPE, r1.FAVORITES, r1.ADDRESS, ROUND(AVG(r2.REVIEW_SCORE), 2) as SCORE
FROM (SELECT * FROM REST_INFO WHERE ADDRESS LIKE '서울%') as r1
INNER JOIN REST_REVIEW r2
ON r1.REST_ID = r2.REST_ID
# group by에는 별칭이 들어갈 수 없다
GROUP BY r1.REST_ID
ORDER BY SCORE DESC, r1.FAVORITES DESC;
