SELECT 
BOARD_ID,
WRITER_ID,
TITLE,
PRICE,
# 거래 상태를 조건에 맞춰서 변환 
CASE
WHEN STATUS = 'SALE' THEN '판매중'
WHEN STATUS = 'RESERVED' THEN '예약중'
WHEN STATUS = 'DONE' THEN '거래완료'
END as STATUS
FROM USED_GOODS_BOARD
# 2022년 10월 05일에 등록된 게시물 
WHERE CREATED_DATE = '2022-10-05'
ORDER BY BOARD_ID DESC;
